// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using FusionZoho.API.Data.Models;

namespace FusionZoho.API.Data;

public partial class FusionZohoContext : DbContext
{
    public FusionZohoContext(DbContextOptions<FusionZohoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ConvertedFusionToZoho> ConvertedFusionToZohos { get; set; }

    public virtual DbSet<WebJob> WebJobs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ConvertedFusionToZoho>(entity =>
        {
            entity.ToTable("ConvertedFusionToZoho");

            entity.Property(e => e.DateCompleted).HasColumnType("datetime");
            entity.Property(e => e.DateCreated).HasColumnType("datetime");
            entity.Property(e => e.FromFusionJob).IsRequired();
            entity.Property(e => e.ToZohoOrder).IsRequired();
        });

        modelBuilder.Entity<WebJob>(entity =>
        {
            entity.ToTable("WebJob");

            entity.Property(e => e.DateCompleted).HasColumnType("datetime");
            entity.Property(e => e.DateCreated).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}